version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "Newtonsoft.Json"
        versions: ["1.x", "2.x"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
